/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GlobalAhepRouteImport } from './routes/global-ahep'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminGateRouteImport } from './routes/admin-gate'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseIdRouteImport } from './routes/course.$id'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedSchoolAdminRouteImport } from './routes/_authenticated/school-admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCertificateSuccessRouteImport } from './routes/_authenticated/certificate-success'
import { Route as AuthenticatedCertificatePaymentRouteImport } from './routes/_authenticated/certificate-payment'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedLearnCourseIdLevelRouteImport } from './routes/_authenticated/learn.$courseId.$level'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalAhepRoute = GlobalAhepRouteImport.update({
  id: '/global-ahep',
  path: '/global-ahep',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGateRoute = AdminGateRouteImport.update({
  id: '/admin-gate',
  path: '/admin-gate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIdRoute = CourseIdRouteImport.update({
  id: '/course/$id',
  path: '/course/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSchoolAdminRoute =
  AuthenticatedSchoolAdminRouteImport.update({
    id: '/school-admin',
    path: '/school-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificateSuccessRoute =
  AuthenticatedCertificateSuccessRouteImport.update({
    id: '/certificate-success',
    path: '/certificate-success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCertificatePaymentRoute =
  AuthenticatedCertificatePaymentRouteImport.update({
    id: '/certificate-payment',
    path: '/certificate-payment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnCourseIdLevelRoute =
  AuthenticatedLearnCourseIdLevelRouteImport.update({
    id: '/learn/$courseId/$level',
    path: '/learn/$courseId/$level',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-gate': typeof AdminGateRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/global-ahep': typeof GlobalAhepRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/certificate-payment': typeof AuthenticatedCertificatePaymentRoute
  '/certificate-success': typeof AuthenticatedCertificateSuccessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/school-admin': typeof AuthenticatedSchoolAdminRoute
  '/api/health': typeof ApiHealthRoute
  '/course/$id': typeof CourseIdRoute
  '/learn/$courseId/$level': typeof AuthenticatedLearnCourseIdLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-gate': typeof AdminGateRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/global-ahep': typeof GlobalAhepRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/certificate-payment': typeof AuthenticatedCertificatePaymentRoute
  '/certificate-success': typeof AuthenticatedCertificateSuccessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/school-admin': typeof AuthenticatedSchoolAdminRoute
  '/api/health': typeof ApiHealthRoute
  '/course/$id': typeof CourseIdRoute
  '/learn/$courseId/$level': typeof AuthenticatedLearnCourseIdLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-gate': typeof AdminGateRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/global-ahep': typeof GlobalAhepRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/certificate-payment': typeof AuthenticatedCertificatePaymentRoute
  '/_authenticated/certificate-success': typeof AuthenticatedCertificateSuccessRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/school-admin': typeof AuthenticatedSchoolAdminRoute
  '/api/health': typeof ApiHealthRoute
  '/course/$id': typeof CourseIdRoute
  '/_authenticated/learn/$courseId/$level': typeof AuthenticatedLearnCourseIdLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-gate'
    | '/auth'
    | '/courses'
    | '/global-ahep'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/verify'
    | '/admin'
    | '/certificate-payment'
    | '/certificate-success'
    | '/dashboard'
    | '/school-admin'
    | '/api/health'
    | '/course/$id'
    | '/learn/$courseId/$level'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-gate'
    | '/auth'
    | '/courses'
    | '/global-ahep'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/verify'
    | '/admin'
    | '/certificate-payment'
    | '/certificate-success'
    | '/dashboard'
    | '/school-admin'
    | '/api/health'
    | '/course/$id'
    | '/learn/$courseId/$level'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-gate'
    | '/auth'
    | '/courses'
    | '/global-ahep'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/verify'
    | '/_authenticated/admin'
    | '/_authenticated/certificate-payment'
    | '/_authenticated/certificate-success'
    | '/_authenticated/dashboard'
    | '/_authenticated/school-admin'
    | '/api/health'
    | '/course/$id'
    | '/_authenticated/learn/$courseId/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminGateRoute: typeof AdminGateRoute
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRoute
  GlobalAhepRoute: typeof GlobalAhepRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  ApiHealthRoute: typeof ApiHealthRoute
  CourseIdRoute: typeof CourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-ahep': {
      id: '/global-ahep'
      path: '/global-ahep'
      fullPath: '/global-ahep'
      preLoaderRoute: typeof GlobalAhepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-gate': {
      id: '/admin-gate'
      path: '/admin-gate'
      fullPath: '/admin-gate'
      preLoaderRoute: typeof AdminGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$id': {
      id: '/course/$id'
      path: '/course/$id'
      fullPath: '/course/$id'
      preLoaderRoute: typeof CourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/school-admin': {
      id: '/_authenticated/school-admin'
      path: '/school-admin'
      fullPath: '/school-admin'
      preLoaderRoute: typeof AuthenticatedSchoolAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificate-success': {
      id: '/_authenticated/certificate-success'
      path: '/certificate-success'
      fullPath: '/certificate-success'
      preLoaderRoute: typeof AuthenticatedCertificateSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificate-payment': {
      id: '/_authenticated/certificate-payment'
      path: '/certificate-payment'
      fullPath: '/certificate-payment'
      preLoaderRoute: typeof AuthenticatedCertificatePaymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$courseId/$level': {
      id: '/_authenticated/learn/$courseId/$level'
      path: '/learn/$courseId/$level'
      fullPath: '/learn/$courseId/$level'
      preLoaderRoute: typeof AuthenticatedLearnCourseIdLevelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCertificatePaymentRoute: typeof AuthenticatedCertificatePaymentRoute
  AuthenticatedCertificateSuccessRoute: typeof AuthenticatedCertificateSuccessRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSchoolAdminRoute: typeof AuthenticatedSchoolAdminRoute
  AuthenticatedLearnCourseIdLevelRoute: typeof AuthenticatedLearnCourseIdLevelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCertificatePaymentRoute: AuthenticatedCertificatePaymentRoute,
  AuthenticatedCertificateSuccessRoute: AuthenticatedCertificateSuccessRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSchoolAdminRoute: AuthenticatedSchoolAdminRoute,
  AuthenticatedLearnCourseIdLevelRoute: AuthenticatedLearnCourseIdLevelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminGateRoute: AdminGateRoute,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRoute,
  GlobalAhepRoute: GlobalAhepRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  ApiHealthRoute: ApiHealthRoute,
  CourseIdRoute: CourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
